/**
 * Assembles the `Content` object the reducer and the renderer both read.
 *
 * `src/data/{species,maps,trainers,dialogue}.gen.ts` are generated by other
 * work running in parallel and may not exist — or may be mid-write — at any
 * given moment. `import.meta.glob` resolves to an empty object rather than a
 * build error when a pattern matches nothing, so this file (and `npm run
 * build`) never breaks because a table hasn't landed yet. Every table is
 * duck-typed before use; anything that doesn't look right falls back to the
 * tiny placeholder roster below, so `npm run dev` always boots and always
 * renders something. `usingPlaceholder` records which tables actually got
 * the real data, for a one-line startup log — never for game logic.
 */

import type { Species, Move, BaseStats, Family } from '../core/creature.ts';
import type { Content, TrainerDef } from '../core/game.ts';
import type { Dex } from '../core/battle.ts';
import type { GameMap, World, NpcDef } from '../core/world.ts';
import { Tile } from '../core/world.ts';
import { MOVE_LIST } from '../data/moves.gen.ts';

// ---------------------------------------------------------------------------
// Defensive loaders for the generated tables
// ---------------------------------------------------------------------------

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null;
}

function firstModule(glob: Record<string, unknown>): unknown {
  for (const key in glob) return glob[key];
  return undefined;
}

const speciesGlob = import.meta.glob('../data/species.gen.ts', { eager: true });
function loadSpecies(): readonly Species[] | null {
  const mod = firstModule(speciesGlob);
  if (!isRecord(mod)) return null;
  const list = mod['SPECIES_LIST'];
  if (!Array.isArray(list) || list.length === 0) return null;
  const first: unknown = list[0];
  if (
    !isRecord(first) ||
    typeof first['id'] !== 'string' ||
    typeof first['name'] !== 'string' ||
    !isRecord(first['base']) ||
    !Array.isArray(first['learnset'])
  ) {
    return null;
  }
  return list as readonly Species[];
}

const mapsGlob = import.meta.glob('../data/maps.gen.ts', { eager: true });
function looksLikeMap(v: unknown): v is GameMap {
  return (
    isRecord(v) &&
    typeof v['id'] === 'string' &&
    typeof v['width'] === 'number' &&
    typeof v['height'] === 'number' &&
    v['tiles'] instanceof Uint8Array
  );
}
function loadWorld(): World | null {
  const mod = firstModule(mapsGlob);
  if (!isRecord(mod)) return null;
  const worldExport = mod['WORLD'];
  if (isRecord(worldExport) && typeof worldExport['map'] === 'function') {
    // Trust WORLD.map exists and returns GameMap-shaped values per the
    // maps.gen.ts contract; a bad implementation would surface at first use,
    // same as any other runtime data error.
    return worldExport as unknown as World;
  }
  const maps = mod['MAPS'];
  if (isRecord(maps)) {
    const values = Object.values(maps);
    const first = values[0];
    if (looksLikeMap(first)) {
      const table = maps as Record<string, GameMap>;
      const fallbackId = first.id;
      return {
        map(id: string): GameMap {
          return table[id] ?? table[fallbackId] ?? first;
        },
      };
    }
  }
  return null;
}

const trainersGlob = import.meta.glob('../data/trainers.gen.ts', { eager: true });
function loadTrainers(): Readonly<Record<string, TrainerDef>> | null {
  const mod = firstModule(trainersGlob);
  if (!isRecord(mod)) return null;
  const table = mod['TRAINERS'];
  if (!isRecord(table)) return null;
  const first: unknown = Object.values(table)[0];
  if (!isRecord(first) || typeof first['id'] !== 'string' || !Array.isArray(first['team'])) return null;
  return table as Readonly<Record<string, TrainerDef>>;
}

const dialogueGlob = import.meta.glob('../data/dialogue.gen.ts', { eager: true });
function loadDialogue(): Readonly<Record<string, readonly string[]>> | null {
  const mod = firstModule(dialogueGlob);
  if (!isRecord(mod)) return null;
  const table = mod['DIALOGUE'];
  if (!isRecord(table)) return null;
  return table as Readonly<Record<string, readonly string[]>>;
}

// ---------------------------------------------------------------------------
// Placeholder roster — just enough to boot, walk around, and fight
// ---------------------------------------------------------------------------

function stats(hp: number, atk: number, def: number, spa: number, spd: number, spe: number): BaseStats {
  return { hp, atk, def, spa, spd, spe };
}

function hashId(id: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < id.length; i++) {
    h ^= id.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

function placeholderSpecies(opts: {
  id: string;
  dex: number;
  name: string;
  animal: string;
  family: Family;
  types: readonly [import('../core/types.ts').FeralType] | readonly [import('../core/types.ts').FeralType, import('../core/types.ts').FeralType];
  base: BaseStats;
  moves: readonly string[];
}): Species {
  return {
    id: opts.id,
    dex: opts.dex,
    name: opts.name,
    animal: opts.animal,
    family: opts.family,
    types: opts.types,
    stage: 'pup',
    archetype: 'allrounder',
    base: opts.base,
    learnset: opts.moves.map((move, i) => ({ level: i === 0 ? 1 : i * 4 + 1, move })),
    expYield: 60,
    catchRate: 190,
    dexEntry: `A placeholder ${opts.animal}, standing in until the real dex entry lands.`,
    spriteSeed: hashId(opts.id),
  };
}

const PLACEHOLDER_SPECIES: readonly Species[] = [
  placeholderSpecies({
    id: 'winter_pup', dex: 1, name: 'Winter', animal: 'husky', family: 'canid',
    types: ['Fang', 'Frost'], base: stats(42, 44, 34, 28, 30, 46),
    moves: ['hamstring', 'frost_nip', 'takedown'],
  }),
  placeholderSpecies({
    id: 'baloo_pup', dex: 2, name: 'Baloo', animal: 'husky', family: 'canid',
    types: ['Fang', 'Ember'], base: stats(46, 42, 36, 30, 28, 40),
    moves: ['hamstring', 'dust_kick', 'scorched_charge'],
  }),
  placeholderSpecies({
    id: 'plato_pup', dex: 3, name: 'Plato', animal: 'tabby cat', family: 'felid',
    types: ['Claw', 'Hearth'], base: stats(38, 40, 30, 34, 32, 48),
    moves: ['swipe', 'nudge', 'pounce'],
  }),
  placeholderSpecies({
    id: 'fen_hare', dex: 4, name: 'Fen Hare', animal: 'hare', family: 'rodent',
    types: ['Claw'], base: stats(32, 34, 24, 22, 24, 50),
    moves: ['swipe', 'pounce'],
  }),
];

// ---------------------------------------------------------------------------
// Placeholder world — a house, a lodge, and a small demo route. The tall
// grass patch has a 100% encounter rate so the battle screen is reachable
// within a step or two, not left to chance.
// ---------------------------------------------------------------------------

function grid(w: number, h: number, fill: number): Uint8Array {
  const t = new Uint8Array(w * h);
  t.fill(fill);
  return t;
}

function rect(t: Uint8Array, w: number, x0: number, y0: number, x1: number, y1: number, v: number): void {
  for (let y = y0; y <= y1; y++) {
    for (let x = x0; x <= x1; x++) t[y * w + x] = v;
  }
}

function set(t: Uint8Array, w: number, x: number, y: number, v: number): void {
  t[y * w + x] = v;
}

function buildHouse(): GameMap {
  const w = 9;
  const h = 8;
  const t = grid(w, h, Tile.Wall);
  rect(t, w, 1, 1, w - 2, h - 2, Tile.Floor);
  rect(t, w, 1, 1, 2, 2, Tile.Bed);
  rect(t, w, 5, 1, 7, 1, Tile.Table);
  rect(t, w, 3, 3, 5, 5, Tile.Carpet);
  set(t, w, 4, h - 1, Tile.Door);
  return {
    id: 'fenmark_house',
    name: 'Astacio House',
    width: w,
    height: h,
    tiles: t,
    warps: [{ x: 4, y: h - 1, toMap: 'fenmark_town', toX: 8, toY: 12 }],
    npcs: [],
    encounters: null,
    indoor: true,
    music: 'home',
  };
}

function buildLodge(): GameMap {
  const w = 8;
  const h = 7;
  const t = grid(w, h, Tile.Wall);
  rect(t, w, 1, 1, w - 2, h - 2, Tile.Floor);
  rect(t, w, 2, 2, 5, 2, Tile.Counter);
  rect(t, w, 2, 4, 5, 4, Tile.Carpet);
  set(t, w, 4, h - 1, Tile.Door);
  const npcs: NpcDef[] = [
    {
      id: 'lodge_keeper', kind: 'healer', x: 3, y: 2, facing: 'down',
      sprite: 'keeper', name: 'Keeper', sight: 0, dialogue: 'lodge_heal',
    },
  ];
  return {
    id: 'fenmark_lodge',
    name: 'Fenmark Lodge',
    width: w,
    height: h,
    tiles: t,
    warps: [{ x: 4, y: h - 1, toMap: 'fenmark_town', toX: 8, toY: 12 }],
    npcs,
    encounters: null,
    indoor: true,
    music: 'indoor',
  };
}

function buildTown(): GameMap {
  const w = 17;
  const h = 15;
  const t = grid(w, h, Tile.Tree);
  rect(t, w, 1, 1, w - 2, h - 2, Tile.Grass);
  rect(t, w, 7, 1, 9, h - 2, Tile.Path);
  rect(t, w, 1, 12, w - 2, 13, Tile.Path);
  rect(t, w, 3, 3, 5, 5, Tile.Water);
  set(t, w, 4, 2, Tile.Bridge);
  rect(t, w, 2, 6, 2, 6, Tile.Sand);
  rect(t, w, 3, 6, 5, 6, Tile.Sand);
  rect(t, w, 11, 3, 13, 5, Tile.TallGrass);
  rect(t, w, 6, 9, 8, 10, Tile.Flower);
  set(t, w, 10, 9, Tile.Rock);
  set(t, w, 11, 10, Tile.Rock);
  rect(t, w, 12, 8, 14, 8, Tile.Fence);
  rect(t, w, 12, 9, 14, 11, Tile.House);
  set(t, w, 13, 11, Tile.Door);
  set(t, w, 13, 7, Tile.Sign);
  rect(t, w, 1, 2, 2, 3, Tile.Snow);
  set(t, w, 8, 6, Tile.LedgeDown);
  set(t, w, 8, 5, Tile.Grass);
  const npcs: NpcDef[] = [
    {
      id: 'town_talker', kind: 'talker', x: 6, y: 9, facing: 'down',
      sprite: 'villager', name: 'Villager', sight: 0, dialogue: 'town_greeting',
    },
  ];
  return {
    id: 'fenmark_town',
    name: 'Fenmark',
    width: w,
    height: h,
    tiles: t,
    warps: [
      { x: 8, y: 12, toMap: 'fenmark_house', toX: 4, toY: 6 },
    ],
    npcs,
    encounters: { rate: 1, slots: [{ species: 'fen_hare', min: 3, max: 5, weight: 1 }] },
    indoor: false,
    music: 'route',
  };
}

function buildPlaceholderWorld(): World {
  const maps = new Map<string, GameMap>([
    ['fenmark_house', buildHouse()],
    ['fenmark_lodge', buildLodge()],
    ['fenmark_town', buildTown()],
  ]);
  return {
    map(id: string): GameMap {
      return maps.get(id) ?? buildHouse();
    },
  };
}

const PLACEHOLDER_DIALOGUE: Readonly<Record<string, readonly string[]>> = {
  intro: [
    'Fenmark, in the rain, same as always.',
    'The real script has not loaded yet, but the road is still the road.',
  ],
  lodge_heal: ['Rest up. On the house, this once.'],
  town_greeting: ['Nice weather, if you like rain.'],
};

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

const realSpecies = loadSpecies();
const realWorld = loadWorld();
const realTrainers = loadTrainers();
const realDialogue = loadDialogue();

/** Which tables are the real generated data vs. the built-in placeholder. */
export const usingPlaceholder = Object.freeze({
  species: realSpecies === null,
  world: realWorld === null,
  trainers: realTrainers === null,
  dialogue: realDialogue === null,
});

function buildDex(species: readonly Species[], moves: readonly Move[]): Dex {
  const speciesById = new Map(species.map((s) => [s.id, s]));
  const moveById = new Map(moves.map((m) => [m.id, m]));
  return {
    species(id: string): Species {
      const s = speciesById.get(id);
      if (s) return s;
      throw new Error(`content: unknown species "${id}"`);
    },
    move(id: string): Move {
      const m = moveById.get(id);
      if (m) return m;
      throw new Error(`content: unknown move "${id}"`);
    },
  };
}

const trainerTable = realTrainers ?? {};
const dialogueTable = realDialogue ?? PLACEHOLDER_DIALOGUE;

export const content: Content = {
  world: realWorld ?? buildPlaceholderWorld(),
  dex: buildDex(realSpecies ?? PLACEHOLDER_SPECIES, MOVE_LIST),
  dialogue(key: string): readonly string[] {
    const lines = dialogueTable[key];
    return lines && lines.length > 0 ? lines : [];
  },
  trainer(id: string): TrainerDef {
    const t = trainerTable[id];
    if (t) return t;
    throw new Error(`content: unknown trainer "${id}"`);
  },
};
