/* GENERATED by scripts/gen/maps.ts — do not edit by hand. */
import type { TrainerDef } from '../core/game.ts';

export const TRAINERS: Readonly<Record<string, TrainerDef>> = {
  "route1_trainer1": {
    "id": "route1_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "redfox_pup",
        "level": 6
      }
    ],
    "aiLevel": 1,
    "prize": 210,
    "introKey": "npc_gossip_2",
    "defeatKey": "npc_gossip_9"
  },
  "route1_trainer2": {
    "id": "route1_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "greyhound",
        "level": 6
      },
      {
        "species": "komodo_pup",
        "level": 7
      }
    ],
    "aiLevel": 1,
    "prize": 210,
    "introKey": "npc_gossip_3",
    "defeatKey": "npc_gossip_10"
  },
  "gym1_guard1": {
    "id": "gym1_guard1",
    "name": "Sworn Blade",
    "title": "of House Vantry",
    "team": [
      {
        "species": "retriever_adult",
        "level": 8
      },
      {
        "species": "shepherd_pup",
        "level": 9
      }
    ],
    "aiLevel": 2,
    "prize": 520,
    "introKey": "npc_gossip_2",
    "defeatKey": "npc_gossip_7"
  },
  "gym1_guard2": {
    "id": "gym1_guard2",
    "name": "House Second",
    "title": "of House Vantry",
    "team": [
      {
        "species": "fennec_adult",
        "level": 8
      },
      {
        "species": "adder_pup",
        "level": 9
      }
    ],
    "aiLevel": 2,
    "prize": 520,
    "introKey": "npc_gossip_3",
    "defeatKey": "npc_gossip_8"
  },
  "gym1": {
    "id": "gym1",
    "name": "Dara Vantry",
    "title": "Head of House Vantry",
    "team": [
      {
        "species": "shepherd_adult",
        "level": 10
      },
      {
        "species": "husky_sled_adult",
        "level": 10
      },
      {
        "species": "capybara_pup",
        "level": 12
      }
    ],
    "aiLevel": 3,
    "prize": 1700,
    "badge": "fang",
    "introKey": "gym1_intro",
    "defeatKey": "gym1_defeat"
  },
  "route2_trainer1": {
    "id": "route2_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "corgi_adult",
        "level": 11
      }
    ],
    "aiLevel": 1,
    "prize": 300,
    "introKey": "npc_gossip_3",
    "defeatKey": "npc_gossip_10"
  },
  "route2_trainer2": {
    "id": "route2_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "moose_pup",
        "level": 11
      },
      {
        "species": "shepherd_pup",
        "level": 12
      }
    ],
    "aiLevel": 1,
    "prize": 300,
    "introKey": "npc_gossip_4",
    "defeatKey": "npc_gossip_11"
  },
  "gym2_guard1": {
    "id": "gym2_guard1",
    "name": "Sworn Blade",
    "title": "of House Calloway",
    "team": [
      {
        "species": "riverotter_adult",
        "level": 14
      },
      {
        "species": "seaotter_apex",
        "level": 15
      }
    ],
    "aiLevel": 2,
    "prize": 640,
    "introKey": "npc_gossip_3",
    "defeatKey": "npc_gossip_8"
  },
  "gym2_guard2": {
    "id": "gym2_guard2",
    "name": "House Second",
    "title": "of House Calloway",
    "team": [
      {
        "species": "platypus",
        "level": 14
      },
      {
        "species": "seaeagle_adult",
        "level": 15
      }
    ],
    "aiLevel": 2,
    "prize": 640,
    "introKey": "npc_gossip_4",
    "defeatKey": "npc_gossip_9"
  },
  "gym2": {
    "id": "gym2",
    "name": "Ines Calloway",
    "title": "Head of House Calloway",
    "team": [
      {
        "species": "seaeagle_pup",
        "level": 16
      },
      {
        "species": "moose_apex",
        "level": 16
      },
      {
        "species": "kodiak_adult",
        "level": 18
      }
    ],
    "aiLevel": 3,
    "prize": 2200,
    "badge": "tide",
    "introKey": "gym2_intro",
    "defeatKey": "gym2_defeat"
  },
  "route3_trainer1": {
    "id": "route3_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "arcticfox_pup",
        "level": 17
      }
    ],
    "aiLevel": 1,
    "prize": 390,
    "introKey": "npc_gossip_4",
    "defeatKey": "npc_gossip_11"
  },
  "route3_trainer2": {
    "id": "route3_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "husky_sled_pup",
        "level": 17
      },
      {
        "species": "tortoise_adult",
        "level": 18
      }
    ],
    "aiLevel": 1,
    "prize": 390,
    "introKey": "npc_gossip_5",
    "defeatKey": "npc_gossip_12"
  },
  "gym3_guard1": {
    "id": "gym3_guard1",
    "name": "Sworn Blade",
    "title": "of House Ashgrove",
    "team": [
      {
        "species": "fennec_adult",
        "level": 20
      },
      {
        "species": "adder_adult",
        "level": 21
      }
    ],
    "aiLevel": 2,
    "prize": 760,
    "introKey": "npc_gossip_4",
    "defeatKey": "npc_gossip_9"
  },
  "gym3_guard2": {
    "id": "gym3_guard2",
    "name": "House Second",
    "title": "of House Ashgrove",
    "team": [
      {
        "species": "sunbear_adult",
        "level": 20
      },
      {
        "species": "fennec_apex",
        "level": 21
      }
    ],
    "aiLevel": 2,
    "prize": 760,
    "introKey": "npc_gossip_5",
    "defeatKey": "npc_gossip_10"
  },
  "gym3": {
    "id": "gym3",
    "name": "Leonore Ashgrove",
    "title": "Head of House Ashgrove",
    "team": [
      {
        "species": "tortoise_adult",
        "level": 22
      },
      {
        "species": "meerkat",
        "level": 22
      },
      {
        "species": "adder_pup",
        "level": 22
      },
      {
        "species": "caracal_pup",
        "level": 24
      }
    ],
    "aiLevel": 3,
    "prize": 2700,
    "badge": "ember",
    "introKey": "gym3_intro",
    "defeatKey": "gym3_defeat"
  },
  "route4_trainer1": {
    "id": "route4_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "skunk",
        "level": 23
      }
    ],
    "aiLevel": 1,
    "prize": 480,
    "introKey": "npc_gossip_5",
    "defeatKey": "npc_gossip_12"
  },
  "route4_trainer2": {
    "id": "route4_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "tortoise_adult",
        "level": 23
      },
      {
        "species": "retriever_adult",
        "level": 24
      }
    ],
    "aiLevel": 1,
    "prize": 480,
    "introKey": "npc_gossip_6",
    "defeatKey": "npc_gossip_1"
  },
  "gym4_guard1": {
    "id": "gym4_guard1",
    "name": "Sworn Blade",
    "title": "of House Thistle",
    "team": [
      {
        "species": "collie_pup",
        "level": 25
      },
      {
        "species": "blackbear_pup",
        "level": 26
      }
    ],
    "aiLevel": 2,
    "prize": 880,
    "introKey": "npc_gossip_5",
    "defeatKey": "npc_gossip_10"
  },
  "gym4_guard2": {
    "id": "gym4_guard2",
    "name": "House Second",
    "title": "of House Thistle",
    "team": [
      {
        "species": "badger_adult",
        "level": 25
      },
      {
        "species": "tiger_adult",
        "level": 26
      }
    ],
    "aiLevel": 2,
    "prize": 880,
    "introKey": "npc_gossip_6",
    "defeatKey": "npc_gossip_11"
  },
  "gym4": {
    "id": "gym4",
    "name": "Ottiline Thistle",
    "title": "Head of House Thistle",
    "team": [
      {
        "species": "tiger_adult",
        "level": 27
      },
      {
        "species": "terrier_pup",
        "level": 27
      },
      {
        "species": "porcupine_adult",
        "level": 27
      },
      {
        "species": "porcupine_pup",
        "level": 29
      }
    ],
    "aiLevel": 3,
    "prize": 3200,
    "badge": "thorn",
    "introKey": "gym4_intro",
    "defeatKey": "gym4_defeat"
  },
  "route5_trainer1": {
    "id": "route5_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "riverotter_pup",
        "level": 28
      }
    ],
    "aiLevel": 1,
    "prize": 570,
    "introKey": "npc_gossip_6",
    "defeatKey": "npc_gossip_1"
  },
  "route5_trainer2": {
    "id": "route5_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "riverotter_pup",
        "level": 28
      },
      {
        "species": "wolf_adult",
        "level": 29
      }
    ],
    "aiLevel": 1,
    "prize": 570,
    "introKey": "npc_gossip_7",
    "defeatKey": "npc_gossip_2"
  },
  "gym5_guard1": {
    "id": "gym5_guard1",
    "name": "Sworn Blade",
    "title": "of House Wren",
    "team": [
      {
        "species": "harpy_pup",
        "level": 30
      },
      {
        "species": "raven_adult",
        "level": 31
      }
    ],
    "aiLevel": 2,
    "prize": 1000,
    "introKey": "npc_gossip_6",
    "defeatKey": "npc_gossip_11"
  },
  "gym5_guard2": {
    "id": "gym5_guard2",
    "name": "House Second",
    "title": "of House Wren",
    "team": [
      {
        "species": "goose_adult",
        "level": 30
      },
      {
        "species": "owl_adult",
        "level": 31
      }
    ],
    "aiLevel": 2,
    "prize": 1000,
    "introKey": "npc_gossip_7",
    "defeatKey": "npc_gossip_12"
  },
  "gym5": {
    "id": "gym5",
    "name": "Corwin Wren",
    "title": "Head of House Wren",
    "team": [
      {
        "species": "raven_pup",
        "level": 32
      },
      {
        "species": "seaeagle_pup",
        "level": 32
      },
      {
        "species": "goose_adult",
        "level": 32
      },
      {
        "species": "owl_apex",
        "level": 34
      }
    ],
    "aiLevel": 3,
    "prize": 3700,
    "badge": "wing",
    "introKey": "gym5_intro",
    "defeatKey": "gym5_defeat"
  },
  "route6_trainer1": {
    "id": "route6_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "lynx_adult",
        "level": 33
      }
    ],
    "aiLevel": 1,
    "prize": 660,
    "introKey": "npc_gossip_7",
    "defeatKey": "npc_gossip_2"
  },
  "route6_trainer2": {
    "id": "route6_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "arcticfox_pup",
        "level": 33
      },
      {
        "species": "owl_pup",
        "level": 34
      }
    ],
    "aiLevel": 1,
    "prize": 660,
    "introKey": "npc_gossip_8",
    "defeatKey": "npc_gossip_3"
  },
  "gym6_guard1": {
    "id": "gym6_guard1",
    "name": "Sworn Blade",
    "title": "of House Mourne",
    "team": [
      {
        "species": "blackcat_pup",
        "level": 35
      },
      {
        "species": "redfox_adult",
        "level": 36
      }
    ],
    "aiLevel": 2,
    "prize": 1120,
    "introKey": "npc_gossip_7",
    "defeatKey": "npc_gossip_12"
  },
  "gym6_guard2": {
    "id": "gym6_guard2",
    "name": "House Second",
    "title": "of House Mourne",
    "team": [
      {
        "species": "redfox_pup",
        "level": 35
      },
      {
        "species": "blackcat_pup",
        "level": 36
      }
    ],
    "aiLevel": 2,
    "prize": 1120,
    "introKey": "npc_gossip_8",
    "defeatKey": "npc_gossip_1"
  },
  "gym6": {
    "id": "gym6",
    "name": "Sera Mourne",
    "title": "Head of House Mourne",
    "team": [
      {
        "species": "komodo_adult",
        "level": 37
      },
      {
        "species": "komodo_pup",
        "level": 37
      },
      {
        "species": "blackcat_apex",
        "level": 37
      },
      {
        "species": "owl_apex",
        "level": 39
      }
    ],
    "aiLevel": 3,
    "prize": 4200,
    "badge": "gloom",
    "introKey": "gym6_intro",
    "defeatKey": "gym6_defeat"
  },
  "route7_trainer1": {
    "id": "route7_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "stag_pup",
        "level": 38
      }
    ],
    "aiLevel": 1,
    "prize": 750,
    "introKey": "npc_gossip_8",
    "defeatKey": "npc_gossip_3"
  },
  "route7_trainer2": {
    "id": "route7_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "raven_adult",
        "level": 38
      },
      {
        "species": "honeybadger_adult",
        "level": 39
      }
    ],
    "aiLevel": 1,
    "prize": 750,
    "introKey": "npc_gossip_9",
    "defeatKey": "npc_gossip_4"
  },
  "gym7_guard1": {
    "id": "gym7_guard1",
    "name": "Sworn Blade",
    "title": "of House Sable",
    "team": [
      {
        "species": "mainecoon_apex",
        "level": 40
      },
      {
        "species": "polarbear_pup",
        "level": 41
      }
    ],
    "aiLevel": 2,
    "prize": 1240,
    "introKey": "npc_gossip_8",
    "defeatKey": "npc_gossip_1"
  },
  "gym7_guard2": {
    "id": "gym7_guard2",
    "name": "House Second",
    "title": "of House Sable",
    "team": [
      {
        "species": "mainecoon_apex",
        "level": 40
      },
      {
        "species": "arcticfox_apex",
        "level": 41
      }
    ],
    "aiLevel": 2,
    "prize": 1240,
    "introKey": "npc_gossip_9",
    "defeatKey": "npc_gossip_2"
  },
  "gym7": {
    "id": "gym7",
    "name": "Halvard Sable",
    "title": "Head of House Sable",
    "team": [
      {
        "species": "mainecoon_pup",
        "level": 42
      },
      {
        "species": "husky_sled_pup",
        "level": 42
      },
      {
        "species": "lynx_adult",
        "level": 42
      },
      {
        "species": "arcticfox_apex",
        "level": 44
      }
    ],
    "aiLevel": 3,
    "prize": 4700,
    "badge": "frost",
    "introKey": "gym7_intro",
    "defeatKey": "gym7_defeat"
  },
  "route8_trainer1": {
    "id": "route8_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "arcticfox_adult",
        "level": 44
      }
    ],
    "aiLevel": 1,
    "prize": 840,
    "introKey": "npc_gossip_9",
    "defeatKey": "npc_gossip_4"
  },
  "route8_trainer2": {
    "id": "route8_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "badger_adult",
        "level": 44
      },
      {
        "species": "beaver_pup",
        "level": 45
      }
    ],
    "aiLevel": 1,
    "prize": 840,
    "introKey": "npc_gossip_10",
    "defeatKey": "npc_gossip_5"
  },
  "gym8_guard1": {
    "id": "gym8_guard1",
    "name": "Sworn Blade",
    "title": "of House Brack",
    "team": [
      {
        "species": "blackbear_adult",
        "level": 45
      },
      {
        "species": "sunbear_pup",
        "level": 46
      }
    ],
    "aiLevel": 2,
    "prize": 1360,
    "introKey": "npc_gossip_9",
    "defeatKey": "npc_gossip_2"
  },
  "gym8_guard2": {
    "id": "gym8_guard2",
    "name": "House Second",
    "title": "of House Brack",
    "team": [
      {
        "species": "muskox_adult",
        "level": 45
      },
      {
        "species": "badger_apex",
        "level": 46
      }
    ],
    "aiLevel": 2,
    "prize": 1360,
    "introKey": "npc_gossip_10",
    "defeatKey": "npc_gossip_3"
  },
  "gym8": {
    "id": "gym8",
    "name": "Ruen Brack",
    "title": "Head of House Brack",
    "team": [
      {
        "species": "komodo_adult",
        "level": 47
      },
      {
        "species": "wolverine_apex",
        "level": 47
      },
      {
        "species": "beaver_pup",
        "level": 47
      },
      {
        "species": "beaver_apex",
        "level": 49
      }
    ],
    "aiLevel": 3,
    "prize": 5200,
    "badge": "maw",
    "introKey": "gym8_intro",
    "defeatKey": "gym8_defeat"
  },
  "route9_trainer1": {
    "id": "route9_trainer1",
    "name": "Fenwalker",
    "title": "of the road",
    "team": [
      {
        "species": "snowleopard_pup",
        "level": 50
      }
    ],
    "aiLevel": 1,
    "prize": 930,
    "introKey": "npc_gossip_10",
    "defeatKey": "npc_gossip_5"
  },
  "route9_trainer2": {
    "id": "route9_trainer2",
    "name": "Houseless Sword",
    "title": "of the road",
    "team": [
      {
        "species": "polarbear_pup",
        "level": 50
      },
      {
        "species": "sunbear_adult",
        "level": 51
      }
    ],
    "aiLevel": 1,
    "prize": 930,
    "introKey": "npc_gossip_11",
    "defeatKey": "npc_gossip_6"
  },
  "elite_1": {
    "id": "elite_1",
    "name": "Ysolde Vane",
    "title": "of the Cross-Fen",
    "team": [
      {
        "species": "riverotter_pup",
        "level": 52
      },
      {
        "species": "meerkat",
        "level": 52
      },
      {
        "species": "hedgehog_adult",
        "level": 52
      },
      {
        "species": "tiger_apex",
        "level": 52
      },
      {
        "species": "snowleopard_apex",
        "level": 54
      }
    ],
    "aiLevel": 3,
    "prize": 7000,
    "introKey": "elite_1",
    "defeatKey": "elite_1_defeat"
  },
  "elite_2": {
    "id": "elite_2",
    "name": "Marek Auldwin",
    "title": "of the Cross-Fen",
    "team": [
      {
        "species": "wolf_apex",
        "level": 54
      },
      {
        "species": "skunk",
        "level": 54
      },
      {
        "species": "falcon_adult",
        "level": 54
      },
      {
        "species": "falcon_pup",
        "level": 54
      },
      {
        "species": "honeybadger_pup",
        "level": 56
      }
    ],
    "aiLevel": 3,
    "prize": 8000,
    "introKey": "elite_2",
    "defeatKey": "elite_2_defeat"
  },
  "elite_3": {
    "id": "elite_3",
    "name": "Perrin Vosk",
    "title": "of the Cross-Fen",
    "team": [
      {
        "species": "housecat",
        "level": 56
      },
      {
        "species": "pug",
        "level": 56
      },
      {
        "species": "corgi_pup",
        "level": 56
      },
      {
        "species": "capybara_pup",
        "level": 56
      },
      {
        "species": "hedgehog_adult",
        "level": 58
      }
    ],
    "aiLevel": 3,
    "prize": 9000,
    "introKey": "elite_3",
    "defeatKey": "elite_3_defeat"
  },
  "elite_4": {
    "id": "elite_4",
    "name": "Alarice Dunn",
    "title": "of the Cross-Fen",
    "team": [
      {
        "species": "harpy_apex",
        "level": 58
      },
      {
        "species": "stag_pup",
        "level": 58
      },
      {
        "species": "stag_adult",
        "level": 58
      },
      {
        "species": "lion_pup",
        "level": 58
      },
      {
        "species": "harpy_pup",
        "level": 60
      }
    ],
    "aiLevel": 3,
    "prize": 10000,
    "introKey": "elite_4",
    "defeatKey": "elite_4_defeat"
  },
  "champion": {
    "id": "champion",
    "name": "Cass",
    "title": "who took the crown first",
    "team": [
      {
        "species": "tiger_apex",
        "level": 60
      },
      {
        "species": "harpy_apex",
        "level": 60
      },
      {
        "species": "owl_apex",
        "level": 60
      },
      {
        "species": "badger_apex",
        "level": 60
      },
      {
        "species": "polarbear_apex",
        "level": 60
      },
      {
        "species": "baloo_apex",
        "level": 62
      }
    ],
    "aiLevel": 3,
    "prize": 20000,
    "introKey": "champion_intro",
    "defeatKey": "champion_defeat"
  }
};

export function getTrainer(id: string): TrainerDef {
  const t = TRAINERS[id];
  if (!t) throw new Error(`unknown trainer: ${id}`);
  return t;
}

export const GYM_ORDER: readonly string[] = ["gym1","gym2","gym3","gym4","gym5","gym6","gym7","gym8"];
export const BADGE_ORDER: readonly string[] = ["fang","tide","ember","thorn","wing","gloom","frost","maw"];
export const ELITE_ORDER: readonly string[] = ["elite_1","elite_2","elite_3","elite_4","champion"];
